version: "3.8"
services:
  backend:
    image: bookstore          
    container_name: backend
    ports:
      - "8080:8080"

  frontend:
    build: .
    container_name: next-frontend
    ports:
      - "3000:3000"
    environment:

      NEXT_PUBLIC_API_BASE_URL: "http://backend:8080/api"
    command: "npm run dev"
    volumes:
      - ./:/app
      - /app/node_modules
    depends_on:
      - backend
