version: "3.8"
services:
  frontend:
    build: .
    container_name: next-frontend
    ports:
      - "3000:3000"
    environment:
  
      NEXT_PUBLIC_API_BASE_URL: "http://host.docker.internal:8080/api"
    volumes:
      - ./:/app
      - /app/node_modules
    command: "npm run dev"
 
    extra_hosts:
      - "host.docker.internal:host-gateway"
